### ISSUE TITLE
Replace `trace` logs with tracing spans

### ISSUE THREAD

**Issue by nicopap** [HeavyRain266/bevy_fbx#20]
Bevy uses tracing spans for easier debugging of runtimes.

We use the `trace!` macro to check which function we enter/leave. There is absolutely no reason to not use tracing spans instead.

**Comment by HeavyRain266** [comment]
There are two ways to use spans:
1. replace `trace!` with `trace_span!`
2. use scoped spans

not sure which one is better in this case.
