### ISSUE TITLE
Load the scene tree

### ISSUE THREAD

**Issue by nicopap** [HeavyRain266/bevy_fbx#26]
FBX has a scene tree similar to bevy's hierarchy. Currently we do not use it in any way.

The scene tree describes transforms applied to objects. The bistro scene relies on it for example to properly rotate the scene.

Bone transforms are (probably) also described in terms of parent/child relationships, so a solid support of the scene tree is a necessary condition to start supporting animations.

`fbxcel_dom` currently exposes the scene tree as the `Tree` data structure accessible through `Document::tree`. An issue I _think_ this has is that it doesn't expose the tree nodes as `ObjectHandle` (there is good reasons for this), making it impossible to use the "fallback" values  defined at the global level.

- Prerequisite of #13
- Could be helped by https://github.com/lo48576/fbxcel-dom/issues/2

**Comment by heavyrain266** [comment]
I think we should leave animations for a moment, I have tried loading some character models but triangulator have problems with computing concave shapes which are used a lot in rigs.
