### ISSUE TITLE
Incorporate in Space_editor

### ISSUE THREAD

**Issue by naomijub** [HeavyRain266/bevy_fbx#34]
Hey @nicopap 
Are you interested in incorporating this work into SpaceEditor?
You have done quite a lot and we could help you maintain this up to date and develop there

**Comment by heavyrain266** [comment]
Based on our testing from more active development around that plugin, I don't think that it really makes sense to include it. Loader is very much slow (takes minutes for basic stuff), triangulator supports only basic shapes and so on. You will have to resolve all the present issues and mayby even contribute a lot of patches to fbxcel ceate used to parse FBX. One of possibilities to make this loader fast is to use Autodesk's official SDK, for example Remedy uses it in open source project for reading it as geometry from USD without any issues.

As a side note, Autodesk is about to deprecate FBX in favor of Pixar's USD. once they will merge specifc set of features.

**Comment by naomijub** [comment]
That makes sense, thanks
